import esbuild from "esbuild";
import process from "process";
import builtins from "builtin-modules";
import { copyFileSync } from "fs";
import { resolve, dirname } from "path";
import { fileURLToPath } from "url";

const __dirname = dirname(fileURLToPath(import.meta.url));

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = process.argv[2] === "production";

// Development build goes to test vault for integration testing
const testVaultPath = resolve(__dirname, "../vault/test/.obsidian/plugins/markdownbrain");
const outfile = prod ? "dist/main.js" : `${testVaultPath}/main.js`;

const context = await esbuild.context({
	banner: {
		js: banner,
	},
	entryPoints: ["src/main.ts"],
	bundle: true,
	external: [
		"obsidian",
		"electron",
		"@codemirror/autocomplete",
		"@codemirror/collab",
		"@codemirror/commands",
		"@codemirror/language",
		"@codemirror/lint",
		"@codemirror/search",
		"@codemirror/state",
		"@codemirror/view",
		"@lezer/common",
		"@lezer/highlight",
		"@lezer/lr",
		...builtins
	],
	format: "cjs",
	target: "es2018",
	logLevel: "info",
	sourcemap: prod ? false : "inline",
	treeShaking: true,
	outfile: outfile,
	plugins: [
		{
			name: "copy-manifest",
			setup(build) {
				build.onEnd(() => {
					if (!prod) {
						// Copy manifest.json and styles.css to test vault in dev mode
						try {
							copyFileSync(
								resolve(__dirname, "manifest.json"),
								`${testVaultPath}/manifest.json`
							);
							console.log("✓ Copied manifest.json to test vault");
						} catch (e) {
							console.error("Failed to copy manifest.json:", e);
						}

						try {
							copyFileSync(
								resolve(__dirname, "styles.css"),
								`${testVaultPath}/styles.css`
							);
							console.log("✓ Copied styles.css to test vault");
						} catch (e) {
							// styles.css is optional
						}
					}
				});
			}
		}
	]
});

if (prod) {
	await context.rebuild();
	process.exit(0);
} else {
	await context.watch();
	console.log(`\n🔧 Development mode: Building to ${testVaultPath}`);
	console.log("👀 Watching for changes...\n");
}
